language: objective-c
osx_image: xcode8.3
podfile: Podfile
install:
- pod install
- pod update
xcode_workspace: Groby Poznanskie API.xcworkspace
xcode_scheme: Groby Poznanskie API
script: xcodebuild -workspace "Groby Poznanskie API.xcworkspace" -scheme "Groby Poznanskie API" -sdk iphonesimulator -configuration Debug build
